name: mattermost-daily-message
on:
  schedule:
    - cron: '0 8 * * 1-5'
  workflow_dispatch:

jobs:
  daily-message-mattermost:
    runs-on: ubuntu-latest
    steps:
      - name: Post daily message on mattermost
        id: post-daily-message
        env:
          MATTERMOST_ACCESS_TOKEN: ${{ secrets.MATTERMOST_ACCESS_TOKEN }}
          MATTERMOST_CHANNEL_ID: ${{ secrets.MATTERMOST_CHANNEL_ID }}
          MATTERMOST_DAILY_MESSAGE: ${{ vars.MATTERMOST_DAILY_MESSAGE }}
        run: |
          curl -i -X POST -H "Authorization: Bearer ${MATTERMOST_ACCESS_TOKEN}" \
            https://chat.canonical.com/api/v4/posts \
            -d "{\"channel_id\":\"${MATTERMOST_CHANNEL_ID}\", \"message\": \"$MATTERMOST_DAILY_MESSAGE\"}"

  daily-message-matrix:
    runs-on: ubuntu-latest
    container:
      image: golang:1.25
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Run Matrix Sender
        working-directory: ./tools/matrix-daily
        env:
          MATRIX_SERVER: ${{ secrets.MATRIX_SERVER }}
          MATRIX_USER_ID: ${{ vars.MATRIX_USER_ID }}
          MATRIX_ACCESS_TOKEN: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          MATRIX_ROOM_ID: ${{ secrets.MATRIX_ROOM_ID }}
          MATRIX_DAILY_MESSAGE: ${{ vars.MATRIX_DAILY_MESSAGE }}
        run: go run main.go