name: mattermost-daily-message
on:
  schedule:
    - cron: '0 8 * * 1-5'
  workflow_dispatch:

jobs:
  daily-message:
    runs-on: ubuntu-latest
    steps:
      - name: Post daily message
        id: post-daily-message
        env:
          MATTERMOST_ACCESS_TOKEN: ${{ secrets.MATTERMOST_ACCESS_TOKEN }}
          MATTERMOST_CHANNEL_ID: ${{ secrets.MATTERMOST_CHANNEL_ID }}
          MATTERMOST_DAILY_MESSAGE: ${{ vars.MATTERMOST_DAILY_MESSAGE }}
        run: |
          curl -i -X POST -H "Authorization: Bearer ${MATTERMOST_ACCESS_TOKEN}" \
            https://chat.canonical.com/api/v4/posts \
            -d "{\"channel_id\":\"${MATTERMOST_CHANNEL_ID}\", \"message\": \"$MATTERMOST_DAILY_MESSAGE\"}"
